### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by SnarkBoojum** [cornernote/minetest-infinite_chest#2]
The only official release is 1.0.0, and it sports a README.md and a LICENSE claiming BSD-3-clause but source files claiming GPL-3...

It would be nice to release a new version with non-contradictory licensing!

Thanks!

**Comment by cornernote** [comment]
done - https://github.com/cornernote/minetest-infinite_chest/releases/tag/1.0.1

**Comment by SnarkBoojum** [comment]
Thanks -- I can now package it for Debian.
